### ISSUE TITLE
Funcionalidad básica

### ISSUE THREAD

**Issue by hejmsdz** [hejmsdz/node-proxy#1]
Cuando el proxy recibe una solicitud, debe pasarla al servidor destino con todas las cabeceras (teóricamente excepto `Connection`, pero podemos dejar esta parte para más tarde #2) y devolver la respuesta al cliente original.

**Comment by chorrisplot** [comment]
Aún tengo que recordar cómo usar github.
Me instalé el API en VScode, pero aún necesito saber cómo conectar al repositorio.
Por ahora cuelgo la versión que yo tengo de http-proxy aquí.
[http-proxy.txt](https://github.com/hejmsdz/node-proxy/files/1538809/http-proxy.txt)

**Comment by hejmsdz** [comment]
He movido tu commit a la rama feature/basic y juntado tu archivo con ProxyServer.js.
Parece funcionar bien, al menos en los casos más típicos.
Voy a instalar un framework de pruebas en el proyecto.

**Comment by hejmsdz** [comment]
El sistema de pruebas ya está. ¿Has trabajado alguna vez en Test Driven Development?
